default_platform(:ios)

platform :ios do
  
  # 1. Bloco de Autenticação (Híbrido: Local vs Nuvem)
  before_all do
    # Se estiver rodando no GitHub Actions (CI)
    if is_ci
      puts "🤖 Configurando autenticação via Secrets do GitHub..."
      app_store_connect_api_key(
        key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
        issuer_id: ENV["APP_STORE_CONNECT_API_ISSUER_ID"],
        key_content: ENV["APP_STORE_CONNECT_API_KEY_CONTENT"],
        in_house: false
      )
    else
      # Se estiver no seu Mac (Local)
      puts "💻 Configurando autenticação local (api_key.json)..."
      if File.exist?("api_key.json")
        app_store_connect_api_key(
          key_filepath: "api_key.json",
          in_house: false
        )
      end
    end
  end

  # 2. A "Lane" (tarefa) de Beta
  desc "Push a new beta build to TestFlight"
  lane :beta do
    # Garante que os certificados estão baixados (modo leitura para segurança)
    match(type: "appstore", readonly: true)

    # Incrementa o número do build (Build Number)
    increment_build_number(xcodeproj: "Runner.xcodeproj")

    # Compila o app (Gera o .ipa)
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")

    # Envia para o TestFlight
    upload_to_testflight(
      skip_waiting_for_build_processing: true # Não trava esperando a Apple
    )
  end
end