name: Mobile Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - run: flutter pub get

      - name: Create Google Play Key
        run: |
          echo "$GOOGLE_PLAY_JSON_KEY" > android/google_play_key.json
        env:
          GOOGLE_PLAY_JSON_KEY: ${{ secrets.GOOGLE_PLAY_JSON_KEY }}

      - name: iOS Deploy
        working-directory: ios
        run: fastlane deploy
        env:
          APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }}

      - name: Android Deploy
        working-directory: android
        run: fastlane deploy